CREATE TABLE USER
(
  ID 			 INTEGER NOT NULL AUTO_INCREMENT,
  NAME           VARCHAR NOT NULL,
  ROLE	         VARCHAR NOT NULL,
);

CREATE TABLE TASK
(
  ID 		  INTEGER NOT NULL AUTO_INCREMENT,
  TITLE       VARCHAR NOT NULL,
  DESCRIPTION VARCHAR NOT NULL,
  USER_ID     INTEGER,
  END_DATE	  DATE,
  START_DATE  DATE,
  FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE CREDENTIALS
(
  ID        INTEGER NOT NULL AUTO_INCREMENT,
  LOGIN     VARCHAR NOT NULL,
  PASSWORD  VARCHAR NOT NULL,
  USER_ID   INTEGER NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);
