CREATE TABLE USER
(
  ID 			    INTEGER NOT NULL AUTO_INCREMENT,
  NAME        VARCHAR,
  ROLE	      VARCHAR
);

CREATE TABLE TASK
(
  ID 			    INTEGER NOT NULL AUTO_INCREMENT,
  TITLE       VARCHAR,
  DESCRIPTION	VARCHAR,
  USER_ID     INTEGER,
  FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);
