CREATE TABLE USER
(
  ID 			 INTEGER NOT NULL AUTO_INCREMENT,
  NAME           VARCHAR NOT NULL,
  ROLE	         VARCHAR NOT NULL,
);

CREATE TABLE WORK_ORDER
(
  ID 			 INTEGER NOT NULL AUTO_INCREMENT,
  TITLE          VARCHAR NOT NULL,
  DESCRIPTION    VARCHAR NOT NULL
);


CREATE TABLE TASK
(
  ID 		  	INTEGER NOT NULL AUTO_INCREMENT,
  TITLE      	VARCHAR NOT NULL,
  DESCRIPTION 	VARCHAR NOT NULL,
  USER_ID     	INTEGER,
  END_DATE	  	DATE,
  START_DATE  	DATE,
  CREATION_DATE DATE NOT NULL,
  STATUS        VARCHAR NOT NULL,
  WORK_ORDER_ID INTEGER,
  FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  FOREIGN KEY (WORK_ORDER_ID) REFERENCES WORK_ORDER(ID)
);

CREATE TABLE CREDENTIALS
(
  ID        INTEGER NOT NULL AUTO_INCREMENT,
  LOGIN     VARCHAR NOT NULL,
  PASSWORD  VARCHAR NOT NULL,
  USER_ID   INTEGER NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);